const People = [
  {
    id: 1,
    name: "John Doe",
    age: 25,
    sign: "Virgo",
    bio: "Passionate about technology and innovation.",
    image: "https://example.com/user1.jpg",
  },
  {
    id: 2,
    name: "Jane Smith",
    age: 30,
    sign: "Taurus",
    bio: "Loves traveling and exploring new cultures.",
    image: "https://example.com/user2.jpg",
  },
  {
    id: 3,
    name: "Chris Johnson",
    age: 22,
    sign: "Gemini",
    bio: "Avid reader and aspiring writer.",
    image: "https://example.com/user3.jpg",
  },
  // {
  //   id: 4,
  //   name: "Emily Wilson",
  //   age: 28,
  //   sign: "Pisces",
  //   bio: "Passionate about environmental conservation.",
  //   image: "https://example.com/user4.jpg",
  // },
  // {
  //   id: 5,
  //   name: "Michael Brown",
  //   age: 35,
  //   sign: "Scorpio",
  //   bio: "Fitness enthusiast and health advocate.",
  //   image: "https://example.com/user5.jpg",
  // },
  // {
  //   id: 6,
  //   name: "Sarah Lee",
  //   age: 29,
  //   sign: "Libra",
  //   bio: "Foodie and amateur chef.",
  //   image: "https://example.com/user6.jpg",
  // },
  // {
  //   id: 7,
  //   name: "David Martinez",
  //   age: 27,
  //   sign: "Leo",
  //   bio: "Musician and artist.",
  //   image: "https://example.com/user7.jpg",
  // },
  // {
  //   id: 8,
  //   name: "Jessica Taylor",
  //   age: 31,
  //   sign: "Capricorn",
  //   bio: "Animal lover and volunteer.",
  //   image: "https://example.com/user8.jpg",
  // },
  // {
  //   id: 9,
  //   name: "Alex Kim",
  //   age: 26,
  //   sign: "Aquarius",
  //   bio: "Tech geek and gamer.",
  //   image: "https://example.com/user9.jpg",
  // },
  // {
  //   id: 10,
  //   name: "Rachel Chang",
  //   age: 33,
  //   sign: "Sagittarius",
  //   bio: "Adventurer and thrill-seeker.",
  //   image: "https://example.com/user10.jpg",
  // },
  // {
  //   id: 11,
  //   name: "Kevin Johnson",
  //   age: 34,
  //   sign: "Cancer",
  //   bio: "Movie buff and film critic.",
  //   image: "https://example.com/user11.jpg",
  // },
  // {
  //   id: 12,
  //   name: "Amanda White",
  //   age: 23,
  //   sign: "Leo",
  //   bio: "Fashionista and beauty enthusiast.",
  //   image: "https://example.com/user12.jpg",
  // },
  // {
  //   id: 13,
  //   name: "Daniel Garcia",
  //   age: 29,
  //   sign: "Aries",
  //   bio: "Fitness trainer and nutritionist.",
  //   image: "https://example.com/user13.jpg",
  // },
  // {
  //   id: 14,
  //   name: "Lauren Brown",
  //   age: 32,
  //   sign: "Aquarius",
  //   bio: "Yoga instructor and mindfulness coach.",
  //   image: "https://example.com/user14.jpg",
  // },
  // {
  //   id: 15,
  //   name: "Matthew Lee",
  //   age: 27,
  //   sign: "Virgo",
  //   bio: "Software developer and technology enthusiast.",
  //   image: "https://example.com/user15.jpg",
  // },
  // {
  //   id: 16,
  //   name: "Ashley Clark",
  //   age: 26,
  //   sign: "Gemini",
  //   bio: "Art lover and museum enthusiast.",
  //   image: "https://example.com/user16.jpg",
  // },
  // {
  //   id: 17,
  //   name: "Erica Martinez",
  //   age: 30,
  //   sign: "Sagittarius",
  //   bio: "Travel blogger and digital nomad.",
  //   image: "https://example.com/user17.jpg",
  // },
  // {
  //   id: 18,
  //   name: "Justin Kim",
  //   age: 28,
  //   sign: "Libra",
  //   bio: "Guitarist and music composer.",
  //   image: "https://example.com/user18.jpg",
  // },
  // {
  //   id: 19,
  //   name: "Samantha Wilson",
  //   age: 24,
  //   sign: "Pisces",
  //   bio: "Animal rights activist and vegan advocate.",
  //   image: "https://example.com/user19.jpg",
  // },
  // {
  //   id: 20,
  //   name: "Tyler Johnson",
  //   age: 36,
  //   sign: "Capricorn",
  //   bio: "Entrepreneur and startup enthusiast.",
  //   image: "https://example.com/user20.jpg",
  // },
  // {
  //   id: 21,
  //   name: "Olivia Smith",
  //   age: 31,
  //   sign: "Taurus",
  //   bio: "Bookworm and literature enthusiast.",
  //   image: "https://example.com/user21.jpg",
  // },
  // {
  //   id: 22,
  //   name: "Ethan Wilson",
  //   age: 29,
  //   sign: "Leo",
  //   bio: "Photographer and visual artist.",
  //   image: "https://example.com/user22.jpg",
  // },
  // {
  //   id: 23,
  //   name: "Madison Brown",
  //   age: 27,
  //   sign: "Libra",
  //   bio: "Fashion designer and stylist.",
  //   image: "https://example.com/user23.jpg",
  // },
  // {
  //   id: 24,
  //   name: "Noah Johnson",
  //   age: 25,
  //   sign: "Scorpio",
  //   bio: "Outdoor enthusiast and nature lover.",
  //   image: "https://example.com/user24.jpg",
  // },
  // {
  //   id: 25,
  //   name: "Isabella Kim",
  //   age: 33,
  //   sign: "Aries",
  //   bio: "Artificial intelligence researcher.",
  //   image: "https://example.com/user25.jpg",
  // },
  // {
  //   id: 26,
  //   name: "James Martinez",
  //   age: 28,
  //   sign: "Aquarius",
  //   bio: "Film director and screenwriter.",
  //   image: "https://example.com/user26.jpg",
  // },
  // {
  //   id: 27,
  //   name: "Ava Taylor",
  //   age: 26,
  //   sign: "Gemini",
  //   bio: "Fitness model and influencer.",
  //   image: "https://example.com/user27.jpg",
  // },
  // {
  //   id: 28,
  //   name: "Logan Garcia",
  //   age: 30,
  //   sign: "Capricorn",
  //   bio: "Product manager and technology strategist.",
  //   image: "https://example.com/user28.jpg",
  // },
  // {
  //   id: 29,
  //   name: "Mia Lee",
  //   age: 24,
  //   sign: "Virgo",
  //   bio: "Environmental activist and sustainability advocate.",
  //   image: "https://example.com/user29.jpg",
  // },
  // {
  //   id: 30,
  //   name: "Mason Clark",
  //   age: 32,
  //   sign: "Pisces",
  //   bio: "Surfing enthusiast and beach lover.",
  //   image: "https://example.com/user30.jpg",
  // },
  // // Add more users here...
  // {
  //   id: 31,
  //   name: "Emma Wilson",
  //   age: 28,
  //   sign: "Cancer",
  //   bio: "Fashion blogger and style influencer.",
  //   image: "https://example.com/user31.jpg",
  // },
  // {
  //   id: 32,
  //   name: "Jackson Brown",
  //   age: 29,
  //   sign: "Leo",
  //   bio: "DJ and music producer.",
  //   image: "https://example.com/user32.jpg",
  // },
  // {
  //   id: 33,
  //   name: "Sophia Kim",
  //   age: 27,
  //   sign: "Sagittarius",
  //   bio: "Travel photographer and adventure seeker.",
  //   image: "https://example.com/user33.jpg",
  // },
  // {
  //   id: 34,
  //   name: "William Martinez",
  //   age: 26,
  //   sign: "Gemini",
  //   bio: "Graphic designer and digital artist.",
  //   image: "https://example.com/user34.jpg",
  // },
  // {
  //   id: 35,
  //   name: "Grace Taylor",
  //   age: 30,
  //   sign: "Virgo",
  //   bio: "Yoga instructor and meditation coach.",
  //   image: "https://example.com/user35.jpg",
  // },
  // {
  //   id: 36,
  //   name: "Henry Johnson",
  //   age: 32,
  //   sign: "Aries",
  //   bio: "Tech entrepreneur and startup founder.",
  //   image: "https://example.com/user36.jpg",
  // },
  // {
  //   id: 37,
  //   name: "Chloe Lee",
  //   age: 29,
  //   sign: "Libra",
  //   bio: "Fashion model and runway coach.",
  //   image: "https://example.com/user37.jpg",
  // },
  // {
  //   id: 38,
  //   name: "Elijah Garcia",
  //   age: 31,
  //   sign: "Taurus",
  //   bio: "Professional chef and culinary expert.",
  //   image: "https://example.com/user38.jpg",
  // },
  // {
  //   id: 39,
  //   name: "Avery Taylor",
  //   age: 28,
  //   sign: "Capricorn",
  //   bio: "Investment banker and financial analyst.",
  //   image: "https://example.com/user39.jpg",
  // },
  // {
  //   id: 40,
  //   name: "Ella Martinez",
  //   age: 26,
  //   sign: "Pisces",
  //   bio: "Art curator and gallery owner.",
  //   image: "https://example.com/user40.jpg",
  // },
  // // Add more users here...
  // {
  //   id: 41,
  //   name: "Luke Wilson",
  //   age: 29,
  //   sign: "Aquarius",
  //   bio: "Software engineer and coding enthusiast.",
  //   image: "https://example.com/user41.jpg",
  // },
  // {
  //   id: 42,
  //   name: "Lily Kim",
  //   age: 27,
  //   sign: "Cancer",
  //   bio: "Interior designer and home decor enthusiast.",
  //   image: "https://example.com/user42.jpg",
  // },
  // {
  //   id: 43,
  //   name: "Gabriel Clark",
  //   age: 31,
  //   sign: "Sagittarius",
  //   bio: "Freelance writer and blogger.",
  //   image: "https://example.com/user43.jpg",
  // },
  // {
  //   id: 44,
  //   name: "Hailey Garcia",
  //   age: 28,
  //   sign: "Virgo",
  //   bio: "Fitness coach and personal trainer.",
  //   image: "https://example.com/user44.jpg",
  // },
  // {
  //   id: 45,
  //   name: "Owen Taylor",
  //   age: 30,
  //   sign: "Scorpio",
  //   bio: "Digital marketer and social media strategist.",
  //   image: "https://example.com/user45.jpg",
  // },
  // {
  //   id: 46,
  //   name: "Aria Martinez",
  //   age: 32,
  //   sign: "Leo",
  //   bio: "Fashion designer and trendsetter.",
  //   image: "https://example.com/user46.jpg",
  // },
  // {
  //   id: 47,
  //   name: "Carter Johnson",
  //   age: 27,
  //   sign: "Gemini",
  //   bio: "Web developer and UX/UI designer.",
  //   image: "https://example.com/user47.jpg",
  // },
  // {
  //   id: 48,
  //   name: "Aubrey Lee",
  //   age: 29,
  //   sign: "Libra",
  //   bio: "Art enthusiast and museum curator.",
  //   image: "https://example.com/user48.jpg",
  // },
];

export default People;
